### ISSUE TITLE
Version mismatch - How to get the current one?

### ISSUE THREAD

**Issue by mr-manuel** [michaelherger/librespot#12]
Hello,

thank you for all your effort and your time!

I saw now, that the [spotty](https://github.com/michaelherger/spotty) repo was archived and you switched over to this one. Are there any changes to do to get the updates from this repo?

I'm a little bit confused, since in the changelog the latest version is `0.4.2` (probably from the upstream), in the tags there is a version `spotty-v1.3.0` and in LMS I see the version `4.8.8` installed. It would be great, if you can clarify this and tell me how I can be sure, that the correct and up to date version is installed.

### GitHub tags
![grafik](https://github.com/michaelherger/librespot/assets/12592765/c21fb9d5-5c82-41cc-b9ea-f3f8b1df5d9f)

### LMS plugins
![grafik](https://github.com/michaelherger/librespot/assets/12592765/2583fc92-446f-4e97-8070-d408827c82ad)

**Comment by michaelherger** [comment]
`0.4.2` is - as you guessed - the upstream library version I'm based on.
`1.3.0` is the helper application's version, which obviously can differ from the library version and the plugin version.
`4.8.8` is the plugin's version.

The plugin uses the helper application, which in turn uses the library. Therefore the different version numbers.

It's probably odd that I'm managing the helper in the same repository as the library. But that's mostly due to the fact that the application is closely based on the upstream's sample application. This allow(s|ed) me in the past to relatively easily pull in upstream changes. But I can't use the upstream as an external library, as I had to fork it to apply some minor changes to the core functionality of the library.

**Comment by mr-manuel** [comment]
Thanks
